import type { Experience } from './types';

export const experience: Experience[] = [
  {
    company: 'PixelTable',
    component: 'PixelTable',
    role: 'CXO & Principal Engineer',
    start: '2023-08',
    end: null,
    highlights: [
      'Built the official Daggerheart Card Creator with Critical Role and Darrington Press',
      'Shipped Alice is Missing: Digital Edition',
      'Helped build the underlying platform and stays hands-on in the codebase daily',
      'Owns the user experience across every PixelTable application',
      'Led the build-out of the Support Portal, a shared community hub for every game title',
    ],
    era: 'recent',
  },
  {
    company: 'Sunstate Equipment Co.',
    component: 'Sunstate',
    role: 'Senior Front-End Software Engineer',
    start: '2023-12',
    end: null,
    highlights: [
      'Builds resilient, performant and secure front-end components for the Sunstate experience',
      'Delivers complex features end to end alongside Product in an agile team',
      'Mentors and coaches engineers across the front end',
    ],
    era: 'recent',
  },
  {
    company: 'RiskLens',
    component: 'RiskLens',
    role: 'Senior Front-End Engineer',
    start: '2022-09',
    end: '2023-07',
    highlights: ['Built front-end features for cyber-risk quantification used to justify security investment decisions'],
    era: 'recent',
  },
  {
    company: 'HostPapa',
    component: 'HostPapa',
    role: 'Senior Software Engineer I',
    start: '2021-06',
    end: '2022-07',
    highlights: [
      'Owned technical breakdowns for upcoming front-end projects',
      'Guided front-end developers while shipping tickets every sprint',
    ],
    era: 'recent',
  },
  {
    company: 'Endurance International Group',
    component: 'Endurance',
    role: 'Senior Software Engineer I · Software Engineer I',
    start: '2017-06',
    end: '2021-06',
    highlights: ['Grew from Software Engineer I to Senior Software Engineer I over four years of front-end work'],
    era: 'recent',
  },
  {
    company: 'Off Madison Ave',
    component: 'OffMadisonAve',
    role: 'Senior Developer',
    start: '2016-01',
    end: '2017-06',
    highlights: ['Built MEAN-stack websites for new and existing agency clients'],
    era: 'early',
  },
  {
    company: 'Pearson Embanet',
    component: 'Pearson',
    role: 'Web Developer',
    start: '2015-04',
    end: '2015-11',
    highlights: [
      'Built responsive sites with HTML5, CSS3/Sass and jQuery, much of it in WordPress',
      'Led the team presentation and documentation on responsive email best practices',
    ],
    era: 'early',
  },
  {
    company: 'Arrowhead Advertising',
    component: 'Arrowhead',
    role: 'Front-End Developer',
    start: '2013-07',
    end: '2015-03',
    highlights: ['Developed client websites and internal applications, including a custom video-upload portal with the media team'],
    era: 'early',
  },
  {
    company: 'Dynamic Page Solutions',
    component: 'DynamicPageSolutions',
    role: 'Web Developer',
    start: '2012-02',
    end: '2013-07',
    highlights: ['Built B2C client sites on a proprietary CMS and maintained its custom templating platform'],
    era: 'early',
  },
  {
    company: 'Firesquire.com',
    component: 'Firesquire',
    role: 'Front-End Developer',
    start: '2009-01',
    end: '2012-02',
    highlights: [
      'Turned designs into standards-compliant HTML/CSS and built custom WordPress themes and plugins',
      'Ran client meetings to gather project specs',
    ],
    era: 'early',
  },
  {
    company: 'Independent Contractor',
    component: 'Freelance',
    role: 'Developer',
    start: '2006-05',
    end: '2009-01',
    highlights: ['Built websites start to finish and helped designers shape layouts and wireframes'],
    era: 'early',
  },
];
